const products = [
  {
    title: "Magnetite",
    category: 1,
    price: 89.0,
    img: "../../assets/img/1.jpg",
    band: "Scalene",
    year: 2017,
    id: 0,
  },
  {
    title: "Acabou o Chorare",
    category: 2,
    price: 66.0,
    img: "../../assets/img/2.jpg",
    band: "Novos Baianos",
    year: 1972,
    id: 1,
  },
  {
    title: "Nirvana Discografia",
    category: 3,
    price: 50.0,
    img: "../../assets/img/3.jpg",
    band: "Nirvava",
    year: 1990,
    id: 2,
  },
  {
    title: "Both Sides",
    category: 4,
    price: 22.0,
    img: "../../assets/img/4.jpg",
    band: "Phil Collins",
    year: 1993,
    id: 3,
  },
  {
    title: "Vem morena",
    category: 5,
    price: 55.0,
    img: "../../assets/img/5.jpg",
    band: "Luiz Gonzaga",
    year: 1949,
    id: 4,
  },
  {
    title: "Jesus Chorou",
    category: 6,
    price: 66.0,
    img: "../../assets/img/6.jpg",
    band: "Racionais",
    year: 2002,
    id: 5,
  },
  {
    title: "California Love",
    category: 7,
    price: 75.0,
    img: "../../assets/img/7.jpg",
    band: "Tupac",
    year: 1990,
    id: 6,
  },
  {
    title: "Back in Black",
    category: 8,
    price: 83.0,
    img: "../../assets/img/8.jpg",
    band: "AC/DC",
    year: 1980,
    id: 7,
  },
  {
    title: "Could You be Loved",
    category: 9,
    price: 92.0,
    img: "../../assets/img/9.jpg",
    band: "Bob Marley",
    year: 1980,
    id: 8,
  },
  {
    title: "Riders in the Sky",
    category: 10,
    price: 102.0,
    img: "../../assets/img/10.jpg",
    band: "Johnny Cash",
    year: 1979,
    id: 9,
  },
  {
    title: "Galileu",
    category: 11,
    price: 111.50,
    img: "../../assets/img/11.jpg",
    band: "Fernandinho",
    year: 2015,
    id: 10,
  },
];

const categories = [
  "Todos",
  "Pop",
  "MPB",
  "Forró",
  "Samba",
  "Baião",
  "Rap",
  "Hip-Hop",
  "Rock",
  "Reggae",
  "Country",
  "Gospel",
];
